# Required by Read The Docs
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: doc/userguide/requirements.txt

sphinx:
  builder: html
  configuration: doc/userguide/conf.py
  fail_on_warning: false

formats: all
